name: exercise_5
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=1.3.0         # Changed version
  - pip=21.0.1           # Changed version
  - pyarrow=17.0.0        # Changed version
  - numpy=1.20.1         # Added numpy package
  - pip:
      - wandb==0.17.7    # Changed version
