wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.17.7
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1724361835
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 23
      4: 3.8.19
      5: 0.17.7
      8:
      - 4
      - 5
      13: darwin-arm64
